const LOGIN         = "USER_LOGING";
const LOGOUT        = "USER_LOGOUT";
const SIGN          = "USER_SIGN";
const LOGINGOOGLE   = "USER_LOGINGOOGLE";

const SETNAME   = "USER_SETNAME";
const SETEMAIL  = "USER_SETEMAIL";
const SETPHONE  = "USER_SETPHONE";
const SETLOGGED = "USER_SETLOGGED";


export {LOGIN, LOGOUT, SIGN, SETNAME, SETEMAIL, SETPHONE, SETLOGGED, LOGINGOOGLE};